### ISSUE TITLE
Cordova Installation for ios error

### ISSUE THREAD

**Issue by NeelSinha** [CAAPIM/Cordova-MAS-Foundation#119]
While installing the plugin in Cordova, I'm not able to install it for the ios platform.

here's the error I'm getting 

```Failed to install 'Cordova-plugin-mas-core': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/neerajs/Sites/projects/develapme/mobile-app-v2/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
```

`pod: Command failed with exit code 1`

**Comment by manutripathi82** [comment]
Hi Neel,
             The information provided is not much to decipher the issue. If you are existing customer of Broadcom(CA Technologies), it would be better to raise a Support ticket. That way it will be easier for us to coordinate on this issue.
Make sure to share the below information about your environment in the Support Ticket

- CA API Gateway version.
- OTK and MAG server version
- CA Mobile SDK for Cordova version
- The complete stack trace of the issue

**Comment by manutripathi82** [comment]
Closing the issue, since no response from a long time
